### PR TITLE
Add 404 Page

### PR DESCRIPTION
**Pull request by e-coders**
**Resolves**

Resolves #
I've been seen the 404 theme in javascript code editor, To add a real working functionallity with the page, this is the request. Please merge then any pages under this website which don't exist will show this 404 theme https://coderedits.github.io/404-Error/.

**Changes**

**Reason for changes**

These changes are added for functionallity with the 404 error.

**Tests**

The test is already work with 5+ websites. This worked on my website, @Educational-Websites, @LexkingOfficial and a lot more!

### CODE REVIEW

**Review by ZI-Youtuber — CHANGES_REQUESTED** [review]
Can you pls explain @e-coders what this file '404.htaccess' does to the 404 error page?

**Comment by e-coders** [comment]
A htaccess file is a website configuration file. It can be used for making 404 pages, redirecting one to an other page and doing more. You can merge this, And don't worry! This is a nice snnipet, work for all pages what doesn't exists.

**Review by ZI-Youtuber — APPROVED** [review]
@e-coders Thank you soo much for your contribution! Pls remember to join our discord server if you wish to : https://discord.gg/FEMJbasHJq

**Comment by e-coders** [comment]
Thanks! But Discord occur a fatal JS error.

**Pull request merged**
